service: test-service

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  localPath: "../lib/index.js"
  modules:
    - ""
functions:
  hello:
    handler: handler.hello
    events:
      - evSchedule:
          rate:
            - rate(5 minutes)
          name: test-crontab
          timezone: Asia/Kolkata
          input:
            prop1: value1
            prop2: value2
validate: true
